name: pyodi
channels:
  - anaconda
  - plotly
dependencies:
  - python=3.6
  - cython
  - numpy
  - matplotlib
  - pandas
  - flake8
  - pytest
  - scikit-learn
  - numba
  - pillow
  - plotly-orca
  - pip:
      - ensemble_boxes
      - typer
      - loguru
      - plotly
      - psutil
      - pre-commit
      - mypy
      - black
      - isort
      - git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
      - mkdocs
      - mkdocs-material
      - mkdocstrings
